numerous fixes

diff --git a/toggle_mdns_announce b/toggle_mdns_announce
--- a/toggle_mdns_announce
+++ b/toggle_mdns_announce
@@ -1,32 +1,161 @@
 #!/bin/sh
 set -e
 
-case "$(sw_vers -productVersion)" in
-10.[6-9]*) # <= Mountain Lion 
-  if defaults read /System/Library/LaunchDaemons/com.apple.mDNSResponder ProgramArguments | grep -q Multicast; then
-    sudo /usr/libexec/PlistBuddy -c 'Delete :ProgramArguments:2' /System/Library/LaunchDaemons/com.apple.mDNSResponder.plist
-    VISIBLE=1
-  else
-    sudo /usr/libexec/PlistBuddy -c 'Add :ProgramArguments: string -NoMulticastAdvertisements' /System/Library/LaunchDaemons/com.apple.mDNSResponder.plist
-    unset VISIBLE
-  fi
-  sudo launchctl unload /System/Library/LaunchDaemons/com.apple.mDNSResponder.plist
-  sudo launchctl load /System/Library/LaunchDaemons/com.apple.mDNSResponder.plist
-  ;;
+if [ "$UID" != 0 ]; then
+  echo 'Rerunning as root' >&2
+  exec sudo "$0" "$@"
+fi
 
+# --- constants
+
+VISIBLE=0
+INVISIBLE=1
+PF_INCLUDE_RULE='include "/etc/pf.conf.mdns-disable"'
+OSX_VER="$(sw_vers -productVersion)"
+
+# --- functions
+
+get_app_firewall() {
+  /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate | grep -q 'enabled'
+}
+
+ask() {
+  unset ANS
+  read -p "$@ (potentially network/app/security disruptive) ? [Yn] " ANS
+  if [ "$ANS" != y ] && [ "$ANS" != Y ]; then
+    echo 'User abort' >&2
+    exit 1
+  fi
+}
+
+# $1 is on or off
+set_app_firewall() { 
+  if get_app_firewall; then
+    if [ "$1" = on ]; then
+      return
+    fi
+  else
+    if [ "$1" = off ]; then
+      return
+    fi
+  fi
+  case "$1" in 
+    on) ask 'Enable Application Firewall'
+      ;;
+    off) ask 'Disable Application Firewall'
+      ;;
+  esac
+  /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate "$1" -k
+}
+
+pf_enabled() {
+  pfctl -s info | grep -q '^Status: Enabled'
+}
+
+pf_enable() {
+  if pf_enabled; then
+    return
+  fi
+  ask 'Enable pf firewall'
+  pfctl -Ef /etc/pf.conf # increment the counter, not just enable it
+  if [ -d d /Applications/Server.app/ ]; then
+     /Applications/Server.app/Contents/ServerRoot/usr/sbin/serverctl enable service=com.apple.afctl
+     if [ -n "$YOSEMITE_OR_NEWER" ]; then
+       /Applications/Server.app/Contents/ServerRoot/usr/libexec/afctl -c 
+     fi
+     /Applications/Server.app/Contents/ServerRoot/usr/libexec/afctl -f
+     /usr/libexec/PlistBuddy 'Add :ProgramArguments: string -E' /System/Library/LaunchDaemons/com.apple.pfctl.plist 
+  fi 
+}
+
+
+pf_conf_has_include_rule() {
+   grep -q "$PF_INCLUDE_RULE" /etc/pf.conf
+}
+
+pf_conf_rule_enabled() {
+   grep -q "^$PF_INCLUDE_RULE" /etc/pf.conf
+}
+
+pf_reload() {
+  pf_enable
+  pfctl -f /etc/pf.conf 2>/dev/null
+}
+
+pf_rules_toggle() {
+  if pf_conf_has_include_rule; then
+    # existing installation
+    if pf_conf_rule_enabled; then
+       # make visible
+       sed -i '' "s%^$PF_INCLUDE_RULE%# $PF_INCLUDE_RULE%" /etc/pf.conf # disable rules
+       pf_reload
+       RESULT=$VISIBLE
+     else
+       # make invisible
+       set_app_firewall on
+       sed -i '' "s%^#.*$PF_INCLUDE_RULE%$PF_INCLUDE_RULE%" /etc/pf.conf # enable rules
+       pf_reload
+       RESULT=$INVISIBLE
+     fi
+  else
+    set_app_firewall on
+    # new installation, make invisible by default
+    tee /etc/pf.conf.mdns-disable << 'PF_CONF_MDNS_DISABLE' >/dev/null
+# /etc/pf.conf.mdns-disable
+# block mulicast dns (bonjour/avahi/mdns)
+block quick inet proto {tcp,udp} from any to any port mdns
+block quick inet6 proto {tcp,udp} from any to any port mdns
+block quick inet from 224.0.0.251 to any
+block quick inet6 from FF02::FB to any
+block quick inet from any to 224.0.0.251 # these might be redundant
+block quick inet6 from any to FF02::FB   #
+PF_CONF_MDNS_DISABLE
+    echo "$PF_RULE" | tee -a /etc/pf.conf >/dev/null # add rule
+    pf_reload
+    RESULT=$INVISIBLE
+  fi
+}
+
+
+mDNSResponder_toggle() {
+  DOMAIN='/System/Library/LaunchDaemons/com.apple.mDNSResponder'
+  PLIST="$DOMAIN.plist"
+  if defaults read "$DOMAIN" ProgramArguments | grep -q Multicast; then
+    /usr/libexec/PlistBuddy -c 'Delete :ProgramArguments:2' "$PLIST"
+    RESULT=$VISIBLE
+  else
+    /usr/libexec/PlistBuddy -c 'Add :ProgramArguments: string -NoMulticastAdvertisements' "$PLIST"
+    RESULT=$INVISIBLE
+  fi
+  ask 'Restart mDNSResponder'
+  launchctl unload "$PLIST"
+  launchctl load "$PLIST"
+}
+
+
+# --- code
+
+
+case "$OSX_VER" in
+10.[6-9]*) # <= Mountain Lion 
+  unset YOSEMITE_OR_NEWER
+  mDNSResponder_toggle
+  ;;
 
 10.10*) # Yosemite only
 #  if defaults read /System/Library/LaunchDaemons/com.apple.discoveryd ProgramArguments | grep -q no-multicast; then
-#    sudo /usr/libexec/PlistBuddy -c 'Delete :ProgramArguments:9' /System/Library/LaunchDaemons/com.apple.discoveryd.plist
+#    /usr/libexec/PlistBuddy -c 'Delete :ProgramArguments:9' /System/Library/LaunchDaemons/com.apple.discoveryd.plist
 #    VISIBLE=1
 #  else
-#    sudo /usr/libexec/PlistBuddy -c 'Add :ProgramArguments: string --no-multicast' /System/Library/LaunchDaemons/com.apple.discoveryd.plist
+#    /usr/libexec/PlistBuddy -c 'Add :ProgramArguments: string --no-multicast' /System/Library/LaunchDaemons/com.apple.discoveryd.plist
 #    VISIBLE=0
 #  fi
-#  sudo launchctl unload /System/Library/LaunchDaemons/com.apple.discoveryd.plist
-#  sudo launchctl load /System/Library/LaunchDaemons/com.apple.discoveryd.plist
+#  launchctl unload /System/Library/LaunchDaemons/com.apple.discoveryd.plist
+#  launchctl load /System/Library/LaunchDaemons/com.apple.discoveryd.plist
 #
 #
+
+  YOSEMITE_OR_NEWER=1
   cat << 'BROKEN' >&2
 
 
@@ -39,86 +168,20 @@ case "$(sw_vers -productVersion)" in
 
 BROKEN
 
-   if sudo pfctl -s info | grep -q '^Status: Enabled'; then
-     echo 'pf enabled'
-     PF_ENABLED=1
-   else
-     echo 'pf disabled'
-     unset PF_ENABLED
-   fi
+  pf_rules_toggle
 
-   if sudo pfctl -s rules | grep -q 'port = 5353$'; then
-     echo 'custom pf rules present'
-     PF_RULES_ACTIVE=1
-   else
-     echo 'custom pf rules missing'
-     unset PF_RULES_ACTIVE
-   fi
-
-   if [ -n "$PF_ENABLED" ] && [ -n "$PF_RULES_ACTIVE" ]; then
-     VISIBLE=1
-   else
-     unset VISIBLE
-   fi
-
-   PF_RULE='include "/etc/pf.conf.mdns-disable"'
-
-   if ! sudo grep -q "$PF_RULE" /etc/pf.conf; then
-     echo 'new installation'
-     # new installation
-
-sudo tee /etc/pf.conf.mdns-disable << 'PF_CONF_MDNS_DISABLE' >/dev/null
-# /etc/pf.conf.mdns-disable
-# block mulicast dns (bonjour/avahi/mdns)
-block quick inet proto {tcp,udp} from any to any port mdns
-block quick inet6 proto {tcp,udp} from any to any port mdns
-block quick inet from 224.0.0.251 to any
-block quick inet6 from FF02::FB to any
-block quick inet from any to 224.0.0.251 # these might be redundant
-block quick inet6 from any to FF02::FB   #
-PF_CONF_MDNS_DISABLE
-
-     if [ -z "$VISIBLE" ]; then
-       # make invisible
-       echo "$PF_RULE" | sudo tee -a /etc/pf.conf >/dev/null # add rules
-     else
-       # make visible
-       echo "# $PF_RULE" | sudo tee -a /etc/pf.conf >/dev/null # add disabled rules
-     fi
-
-   else # existing installation
-     echo 'existing installation'
-     set -x
-     if [ -z "$VISIBLE" ]; then
-       # make invisible
-       sudo sed -i '' "s%^#.*$PF_RULE%$PF_RULE%" /etc/pf.conf # enable rules
-     else
-       # make visible
-       sudo sed -i '' "s%^$PF_RULE%# $PF_RULE%" /etc/pf.conf # disable rules
-     fi
-   fi
-
-   if [ -z "$PF_ENABLED" ]; then
-     cat << 'NOTES' >&2
-
-     Firewall must be enabled for this hack to block Bonjour.
-
-        Systems Preferences > Security & Privacy > Firewall > Turn On Firewall
-
-NOTES
-     exit 1
-   fi
- 
-   sudo pfctl -f /etc/pf.conf 2>/dev/null # reload tables
   ;;
 
 *)
-  echo 'cannot toggle mdns annoucements: unknown platform!' >&2
+  echo "Cannot toggle Bonjour visibility (mdns traffic): unknown OSX version '$OSX_VER' " >&2
   exit 1
 esac
 
-if [ -n "$VISIBLE" ]; then
-  echo 'This computer is now VISIBLE to other computers (multicast dns (mdns) annoucements enabled)'
-else
-  echo 'This computer is now INVISIBLE to other computers (multicast dns (mdns) annoucements disabled)'
-fi
+case "$RESULT" in
+$VISIBLE)
+  echo 'This computer is now VISIBLE to other nearby computers (Bonjour - multicast dns (mdns) annoucements enabled)'
+  ;;
+$INVISIBLE)
+  echo 'This computer is now INVISIBLE to other nearby computers (Bonjour - multicast dns (mdns) annoucements disabled)'
+  ;;
+esac
diff --git a/uninstall_pkg b/uninstall_pkg
--- a/uninstall_pkg
+++ b/uninstall_pkg
@@ -4,12 +4,11 @@ test -n "$DEBUG" && set -x
 
 RECEIPT_DIR='/var/db/receipts'
 
-trap 'RESULT=$?; rm -f "$BOMS"; exit $RESULT' EXIT ERR INT QUIT TERM PIPE HUP
-BOMS="$(mktemp -t uninstall_pkg)"
-
+trap 'RESULT=$?; rm -rf "$BOMS"; exit $RESULT' EXIT ERR INT QUIT TERM PIPE HUP
+BOMS="$(mktemp -d -t uninstall_pkg)"
 
 _rm() {
-  echo "rm -f '$@'"
+  echo "sudo rm -f '$@'"
   if [ -z "$DRY_RUN" ]; then
     sudo rm -f "$@"
   fi
@@ -17,12 +16,25 @@ _rm() {
 
 _rmdir() {
   D="$1"
-  if [ "$D" = . ]; then
+  if [ "$D" = . ]; then # confirm non-recursive delete
     D="$PWD"
-  fi
-  echo "rmdir -p '$D'"
-  if [ -z "$DRY_RUN" ]; then
-    sudo rmdir -p "$D"
+    echo "sudo rm -ir '$D'"
+    if [ -z "$DRY_RUN" ]; then
+      echo '*** Proceed with EXTREME CAUTION, Ctrl-C if unsure ***' >&2
+      echo >&2
+      unset ANS
+      read -p "Recursively delete '$D' ? [Yn] " -u 3 ANS
+      if [ "$ANS" = y ] || [ "$ANS" = Y ]; then
+        sudo rm -rf "$D"
+      else # no
+        echo "Skipping $D" >&2
+      fi
+    fi
+  else # non-recursive delete of dir D only
+    echo "sudo rm -df '$D'"
+    if [ -z "$DRY_RUN" ]; then
+      sudo rm -df "$D"
+    fi
   fi
 }
 
@@ -32,26 +44,30 @@ find "$RECEIPT_DIR" -type f -name "*$1*.bom" | while read -r BOM; do
   PLIST="$(echo "$BOM" | sed 's/\.bom$/.plist/')"
   INSTALL_PREFIX_PATH="/$(defaults read "$PLIST" InstallPrefixPath)"
 
+  lsbom -fls "$BOM" > "$BOMS/files"
+  lsbom -dls "$BOM" | sort -r > "$BOMS/dirs"
   echo
   echo "----- Start '$BOM'"
-  lsbom -fls "$BOM" | sed "s%^%file $INSTALL_PREFIX_PATH%g;s%\./%/%g"
-  lsbom -dls "$BOM" | sed "s%^% dir $INSTALL_PREFIX_PATH%g;s%\./%/%g"
+  sed "s%^%file $INSTALL_PREFIX_PATH%g;s%\./%/%g" < "$BOMS/files"
+  sed "s%^% dir $INSTALL_PREFIX_PATH%g;s%\./%/%g" < "$BOMS/dirs"
   echo "------ End '$BOM'"
   echo
   read -p "Uninstall using '$BOM' ? [Yn] " -u 3 ANS
 
   if [ "$ANS" = y ] || [ "$ANS" = Y ]; then
-    (
-      cd "$INSTALL_PREFIX_PATH"
-      lsbom -fls "$BOM" | while read -r FILENAME; do
-        _rm "$FILENAME"
-      done
-      lsbom -dls "$BOM" | while read -r DIR; do
-        echo "DIR='$DIR'"
-        _rmdir "$DIR"
-      done
-    )
-
-    sudo _rm "$BOM" "$PLIST"
+    if [ -d "$INSTALL_PREFIX_PATH" ]; then
+      (
+        cd "$INSTALL_PREFIX_PATH"
+        while read -r FILENAME; do
+          _rm "$FILENAME"
+        done < "$BOMS/files"
+        while read -r DIR; do
+          _rmdir "$DIR"
+        done < "$BOMS/dirs"
+      )
+    else
+      echo "Missing INSTALL_PREFIX_PATH=${INSTALL_PREFIX_PATH}" >&2
+    fi
+    _rm "$BOM" "$PLIST"
   fi
 done 
